import type { Metadata } from "next";
import localFont from "@next/font/local";

const BMWTypeNextBold = localFont({
  src: "./fonts/BMWTypeNext-Bold.20210426144302.ttf",
});
const BMWTypeNextLight = localFont({
  src: "./fonts/BMWTypeNext-Light.20210426144302.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={BMWTypeNextBold.className}>{children}</body>
    </html>
  );
}
