import type { Metadata } from "next";
import localFont from "@next/font/local";
import { ChakraProvider } from "@chakra-ui/react";

const fonts = localFont({
  src: [
    {
      path: "./fonts/BMWTypeNext-Light.20210426144302.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/BMWTypeNext-Bold.20210426144302.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
